ads/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import AdsCreateView, AdsUpdateView, AdsDeleteView

urlpatterns = patterns('',
                       #url(r'^(?P<pk>\d+)/$', CampaignDetailView.as_view(), name='campaign.detail'),
    url(r'^(?P<pk>\d+)/edit/$', AdsUpdateView.as_view(), name='ads.update'),
    url(r'^(?P<pk>\d+)/delete/$', AdsDeleteView.as_view(), name='ads.delete'),
    url(r'^(?P<campaign_id>\d+)/add/$', AdsCreateView.as_view(), name='ads.create_campaign'),
    url(r'add/$', AdsCreateView.as_view(success_url='/'), name='ads.create'),
)

adsme/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from campaigns.views import  CampaignListView
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', CampaignListView.as_view(), name='home'),
    url(r'^login/$', 'accounts.views.custom_login',
        {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', 'django.contrib.auth.views.logout',
        {'template_name': 'logout.html', 'next_page': '/'}, name='logout'),
    url(r'^social_auth/', include('social_auth.urls')),
    url(r'^account/', include('accounts.urls')),
    url(r'^campaign/', include('campaigns.urls')),
    url(r'^ads/', include('ads.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

if settings.DEBUG:
    urlpatterns += staticfiles_urlpatterns()
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

campaigns/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from .views import CampaignDetailView, CampaignCreateView, CampaignDeleteView, CampaignUpdateView

urlpatterns = patterns('',
    url(r'^(?P<pk>\d+)/$', CampaignDetailView.as_view(), name='campaign.detail'),
    url(r'^(?P<pk>\d+)/edit/$', CampaignUpdateView.as_view(), name='campaign.update'),
    url(r'^(?P<pk>\d+)/delete/$', CampaignDeleteView.as_view(), name='campaign.delete'),
    url(r'add/$', CampaignCreateView.as_view(), name='campaign.create'),
)

ads/models.py
from django.db import models

from campaigns.models import Campaign


class Ads(models.Model):
    campaign = models.ForeignKey(Campaign)
    title = models.CharField(max_length=256)
    body = models.CharField(max_length=256)
    image = models.ImageField(upload_to='ads_images')
    url = models.URLField()
    is_google = models.BooleanField(default=False)
    is_facebook = models.BooleanField(default=False)

campaigns/models.py
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models

CAMPAIGN_STATUS = [
    (0, 'STOP'),
    (1, 'ACTIVE'),
    (2, 'PAUSE')
    ]


class Campaign(models.Model):
    """
    Campaign model.
    currently hold the main data.
    furthermore we can make based on google-campagin or facebook campaign.
    """
    user = models.ForeignKey(User)
    name = models.CharField(max_length=256)
    created_ts = models.DateTimeField(auto_now_add=True)
    status = models.IntegerField(choices=CAMPAIGN_STATUS,
                                 default=1)
    daily_budget = models.IntegerField()
    lifetime_budget = models.IntegerField()
    start_ts = models.DateTimeField()
    end_ts = models.DateTimeField()
    is_google = models.BooleanField(default=False)
    is_facebook = models.BooleanField(default=False)

    def __unicode__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('campaign.detail', kwargs={'pk': self.id})

campaigns/forms.py
from django.forms import ModelForm

from .models import  Campaign


class CampaignForm(ModelForm):
    class Meta:
        model = Campaign
        exclude = ['user']

campaigns/views.py
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from django.utils.decorators import method_decorator

from .forms import CampaignForm
from .models import Campaign


class CampaignListView(ListView):
    model = Campaign
    template_name = 'campaigns/list.html'
    context_object_name = 'objects'
    paginate_by = 10

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CampaignListView, self).dispatch(*args, **kwargs)


class CampaignDetailView(DetailView):
    model = Campaign

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CampaignDetailView, self).dispatch(*args, **kwargs)


class CampaignCreateView(CreateView):
    model = Campaign
    form_class = CampaignForm
    
    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CampaignCreateView, self).dispatch(*args, **kwargs)

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super(CampaignCreateView, self).form_valid(form)


class CampaignDeleteView(DeleteView):
    model = Campaign
    success_url = '/'

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CampaignDeleteView, self).dispatch(*args, **kwargs)


class CampaignUpdateView(UpdateView):
    model = Campaign

    form_class = CampaignForm

    def get_context_data(self, **kwargs):
	context = super(CampaignUpdateView, self).get_context_data(**kwargs)
	context['title'] = 'Update'
	return context

    @method_decorator(login_required)
    def dispatch(self, *args, **kwargs):
        return super(CampaignUpdateView, self).dispatch(*args, **kwargs)

templates/campaigns/campaign_confirm_delete.html
{% extends 'base_main.html' %}

{% block main %}
Are you sure want to delete?
<form method="POST" action="{% url 'campaign.delete' object.id %}">
<p>{% csrf_token %}<button type='submit' class="btn">Yes</button></p>
</form>
<p class="btn"><a href="{% url 'campaign.detail' object.id %}">No</a></p>
{% endblock %}

templates/campaigns/campaign_detail.html
{% extends 'base_main.html' %}
{% load thumbnail %}
{% block main %}
<div class="container">
  <h3 class="pull-left"> Campaign {{ object.name }}</h3>
  <div class="btn-group pull-right" style="margin:10px 0">
    <a class="btn btn-info" href="{% url 'campaign.update' object.id %}">Update Campaign</a>
    <a class="btn btn-info" href="{% url 'campaign.delete' object.id %}">Delete Campaign</a>
    <a class="btn btn-info" href="{% url 'ads.create_campaign' object.id %}">Create ads</a>
  </div>
</div>
<div class="clearfix"><div>
<table class="table">
  <tr>
    <td>Name</td>
    <td>{{ object.name }}</td>
  </tr>
  <tr>
    <td>Created</td>
    <td>{{ object.created_ts }}</td>
  </tr>
  <tr>
    <td>Status</td>
    <td>{{ object.get_status_display }}</td>
  </tr>
  <tr>
    <td>Daily Budget</td>
    <td>{{ object.daily_budget }}</td>
  </tr>
  <tr>
    <td>Lifetime budget</td>
    <td>{{ object.lifetime_budget }}</td>
  </tr>
  <tr>
    <td>Start</td>
    <td>{{ object.start_ts }}</td>
  </tr>
  <tr>
    <td>End</td>
    <td>{{ object.end_ts }}</td>
  </tr>
</table>

<h2>Ads</h2>
{% if object.ads_set.all %}

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Image</th>
      <th>Action</th>
    </tr>
  </thead>
  <tbody>
  {% for ads in object.ads_set.all %}
  <tr>
    <td>{{ ads.title }}</td>
    <td>{{ ads.body }}</td>
    {% thumbnail ads.image "50x50" as im %}
    <td><img src="{{ im.url }}"/></td>
    {% endthumbnail %}
    <td><a href="{% url 'ads.update' ads.id %}" class="btn">Update</a>&nbsp;<a href="{% url 'ads.delete' ads.id %}" class="btn">Delete</a></td>
  </tr>
  </tbody>
  {% endfor %}
</table>
{% endif %}
{% endblock %}

templates/campaigns/campaign_form.html
{% extends 'base_main.html' %}

{% block main %}
<div class="container">
   <h3 class="pull-left"> Campaign Form</h3>
</div>
<div class="clearfix"></div>
<form class="form-horizontal" {% if multipart %}enctype="multipart/form-data"{%endif%} method="{{ method|default:'post' }}" action=".">
  {% include 'form_snippets.html' %}
<div class="control-group">
  <label class="control-label">&nbsp;</label>
  <div class="controls">
    <button type="submit"  class="btn btn-primary" />{{ title|default:'Add' }}</button>
  </div>
</div>
{% endblock %}

templates/campaigns/list.html
{% extends "base_main.html" %}

{% block main %}
<h3>Campaign List</h3>
<table class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th>Created</th>
    </tr>
  </thead>
  <tbody>
    {% for object in objects %}
    <tr>
      <td><a href='{% url "campaign.detail" object.id %}'>{{ object.name }}&nbsp;</a>
      <td>{{ object.created_ts }}
    {% endfor %}
  </tbody>
</table>
<div class="pagination">
    <ul class="step-links">
        {% if objects.has_previous %}
            <li><a href="?page={{ objects.previous_page_number }}">previous</a></li>
        {% endif %}

        <li><span class="current">
            Page {{ objects.number|default:'1' }} of {{ objects.paginator.num_pages|default:'1' }}.
        </span></li>

        {% if objects.has_next %}
            <li><a href="?page={{ objects.next_page_number }}">next</a></li>
        {% endif %}
    </ul>
</div>
{% endblock %}